language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: AKIAJWREF2DZPXOXVI7Q
  bucket: aws-travis-jo
  region: us-west-2
  secret_access_key:
    secure: "xfAcepXcTiFxTGLjeD8COVvD3nLbiXzAUSRz9i5NIhttpFxrLG72wBpAVLWsPfCF7TMuSTxKwZyL22w77/QJdSJJFHkagZ575V+h+GoWTpqulEZ24GJf51gSnmF7cP+DNhSPVxVFInArlw/d0B2ESNJpSdSffvVzslHAKnrfBEcq2oCQff9FqcT4JCEYrNdlRKFPiJzbkaCm2Br1k+TM1v2V3QqCPWJ/G8Aa4gv3b1OJbnFc2ZLWujRKGvs3DMMO8QTJ8g60CaYeEmMRBMQpc1uQQUoZHQOZgQjXyXWTpQJQTMizzzvxe+NJm0JEATMFhS3M5o9nqJv6aZE8S489hSIDEIdTk7xal5aOvb5cWZTS9Jizd0D/0fFzhW5944mncgsdt0/Gsibe7jt+aP/2/EyHnyjUZ7t7D8/tX/UgoBcM6VmB+0OCDkD359zyWHC9VcnB/pYZiEMvWT6MiyCtbv1dknE+ynSkclSIESzj8dMhC75riLm9C7utz1KzempQbRj2gUgSVNU4UB9tzS8MXY0mXKKxOeT4dCgTGIUCsXdhyZLCRZdsYuzDsSMloQQNVOCw8xrinT+XxK2OPsItL5FVmqVzDcRkcIhbA0454ePVJU/n4M33z4psAdUE9V2RwiUhBndDrlkqP7DFSmSjeclcjNI7w7nlKVZmStd45ns="
