language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: AKIAJWREF2DZPXOXVI7Q
  bucket: aws-travis-jo
  region: us-west-2
  secret_access_key:
    secure: wjjAx897XjWdqEPHJvTISfCXdxqOqXfKMeFI3BpSUFCsnqXRw4/PMRIMMKxn/o00weMibxI0pSjPghFiUHAJzM0iMxP70AN2A4ZDvocnJ1j9+mAEoOhK9AWIv/GJ4BV8yxa38+6BGCmSxUMECdE07wbB+T/xfJTesJDMOHdxDWJgU8OIveA4wDdmMog2UbA25Pw9Q0kqp1sjTkZBc7lLBp0wXWk526R8ewEASSDxXp7HR+YbOnDLfSzSIewqkTFl44J9742h6X867Ejk7jXn/rU1mDcOPLIx23lt3jgRoq9V8SbPrzWCxoOrMdmaOluWyzSL3QI23ARKHMnKsgwuCwkT6khx7mtrGg8szWObi1cu6Qr2LCxiR6u6almOrWMnuX5tOjMTMFG34kr5sfmSlXO0xyhqClHUYzdHVJP2VyBEoOJtv1ytqlyMOGVT3jPKFwiDy1fwCvyn+AkLjt/bLEl84ORfVxe+F+nMt+P7yDmFxJ5GOoXzJIhIKOgMrXplTXKcg6BeojAQEUVGzblT+4LfxDBX2ygrUkPSSstT77Ljv/qRacCV0Rz1ijyCu2VNNeR51wwc58zT/e1koRtEraWYBQVd0ovQ5kaVTX/rLd5isBTFu908zRwAr5azdrU8JxsSde2vagrJ/9Yz7SOrGHCU5vIEK4gnA/KWYxQsxTI=
