language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: "AKIAJWREF2DZPXOXVI7Q"
  bucket: "aws-travis-jo"
  region: us-west-2
  secret_access_key:
    secure: "HzCfgRCpb6LnUHzCihBy+2hQfHLZtWGe3iSoyvIuNkeaKxgq0mhT97dkk21Mz5KazdC1iinmYBzdwc7+6UJLmn+1gvNpMfvytqNvjCdjhATP6GztzKwbfv7xik9W83OxnWrQsXBmuG9elps0IqCCuPUbZrzi70BX5L8pOPhSmNiZouKriY8lH7HH/o1LttCVdGhPDAwPd1SkWWgfnYZL+DVTeGXU179WNNCnISx6Y7q9mDb35lepc2fc6sArBvFPLvMAxY9xzxbPl5x83G0E6HjEKk4C1eOwx2+aLikg+uH0v2+1hSmu6IkO9kijur/r3Jdh6J5TQ0uzE846U6s4r0J5VMmdDLbx/m36vmcnpXjRZKyf0kV4tHRJXUO/sycNXtQ3F4y46TdGgYbCgJyHyAdsC/uoFF+k8PYcLKaqn4+uj2MoB1deMf2U4xX9wabij3IfQ441OxQ9VY08h4rf4xALK8/rOJaWEClrgdc0RRdu0AQJwLtkIybEtUDaRLJ7wYrfd1N29bNlqAve67ju4iH7hEo5evu82q+AcFD+9uaaLNAcmUPUOzNSHIfO9lcEvbTZaH7JLFoPf88a+77eyd+oQPe0gDdoKoD6Qdc+AsMRW8CFTVxZ2OsNCeUonWGNQDYRraE3BUJHEZO/kkfe/6ScoNmXnMC4nmnwHUh4T/w="
